### ISSUE TITLE
AWS Secrets should be treated as GitHub Workflow secrets

### ISSUE THREAD

**Issue by burz** [gagoar/invoke-aws-lambda#219]
Currently both `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are not treated as secrets within the GitHub workflow ecosystem. This is a security risk that could lead to these being leaked in logs/etc.

This is probably going to be hard to change since existing users probably are not using a specific version of the workflow but rather following the README example and using `gagoar/invoke-aws-lambda@master`.

**Comment by gagoar** [comment]
Hey @burz. thanks for the issue. What I think we could do, is start using @main for this change, and leave master as just another branch.  I should be using `@main` anyways. That would break nothing on legacy systems and every new comer will get the main version. 

thoughts?

**Comment by burz** [comment]
That seems reasonable to me! Unfortunately it seems like the secret treatment as part of reusable workflows may be a rather recent change since many many actions don't seem to differentiate in terms of their inputs.

**Comment by burz** [comment]
I created [a branch](https://github.com/burz/invoke-aws-lambda/tree/main) on my fork to fix this, if you wouldn't mind creating a `main` branch on your repo, I could send a PR?

Thanks again,
-burz

**Comment by gagoar** [comment]
@burz Thanks for all your help! version 3.3.1 has carries all the changes! and master as well of course.

**Comment by burz** [comment]
Thanks for your help with this @gagoar !
