### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by dmarcucci** [gagoar/invoke-aws-lambda#250]
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by gagoar** [comment]
Hey @dmarcucci `master` has the latest updates that solve this issue. I haven't released a new version tho. So I will do that. 

In the meantime feel free to take `gagoar/invoke-aws-lambda@master` to avoid seeing this problem

**Comment by dmarcucci** [comment]
Hi @gagoar 

I looked [here](https://github.com/gagoar/invoke-aws-lambda/blob/master/src/index.ts#L81) and it seems like it's still being used. Am I not looking in the right place?

**Comment by dmarcucci** [comment]
Sorry, I missed this part:

> Action authors who are using the toolkit should update the @actions/core package to v1.10.0 or greater to get the updated saveState and setOutput functions.

Confirmed this in `package.json`. Will wait for the new version. Thanks!

**Comment by gagoar** [comment]
Hey, @dmarcucci I've released 3.3.2. Try it put, please. Lemme know if this solves your issue.

**Comment by dmarcucci** [comment]
Yep, looks good. Not seeing any more warnings, so I think this is all set.

Thanks!
